"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['venv/spherecrypt/__init__.py']
DATA_FILES = []
OPTIONS = dict(argv_emulation=True, iconfile='swirl.png')

setup(
    name='sphereCrypt',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
